# Generated by Django 5.0 on 2023-12-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0002_movies_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='aaaa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
